export const TEMPLATES = [
  // ── Without Photo ──────────────────────────────────────────────────────
  {
    id: 'minimal-pro',
    name: 'Minimal Pro',
    desc: 'Ultra-clean, typography-first. Big bold name, razor-thin rules.',
    gradient: 'linear-gradient(135deg,#1a1a2e 0%,#16213e 100%)',
    previewBg: '#FFFFFF',
    accentColor: '#0D0D0F',
    hasPhoto: false,
    category: 'Clean',
    emoji: '⬜',
  },
  {
    id: 'bold-edge',
    name: 'Bold Edge',
    desc: 'Strong navy header, 2-column layout, skill tags with sharp borders.',
    gradient: 'linear-gradient(135deg,#1B4FD8 0%,#1e3a8a 100%)',
    previewBg: '#EFF6FF',
    accentColor: '#1B4FD8',
    hasPhoto: false,
    category: 'Professional',
    emoji: '🔷',
  },
  {
    id: 'nordic',
    name: 'Nordic',
    desc: 'Warm cream, elegant serif headings, sophisticated horizontal dividers.',
    gradient: 'linear-gradient(135deg,#78716c 0%,#a8956a 100%)',
    previewBg: '#FAF7F2',
    accentColor: '#8B6914',
    hasPhoto: false,
    category: 'Elegant',
    emoji: '🌿',
  },

  // ── With Photo ─────────────────────────────────────────────────────────
  {
    id: 'portrait',
    name: 'Portrait',
    desc: 'Circular photo in an indigo sidebar. Bold personal branding.',
    gradient: 'linear-gradient(135deg,#6C47FF 0%,#4A2FD9 100%)',
    previewBg: '#EDE9FF',
    accentColor: '#6C47FF',
    hasPhoto: true,
    category: 'Modern',
    emoji: '🟣',
  },
  {
    id: 'magazine',
    name: 'Magazine',
    desc: 'Editorial layout — photo beside name in a full-width header.',
    gradient: 'linear-gradient(135deg,#be185d 0%,#9f1239 100%)',
    previewBg: '#FFF1F5',
    accentColor: '#be185d',
    hasPhoto: true,
    category: 'Creative',
    emoji: '🔴',
  },
  {
    id: 'passport',
    name: 'Passport',
    desc: 'Official-look header with photo left, teal accent strip.',
    gradient: 'linear-gradient(135deg,#0d9488 0%,#0f766e 100%)',
    previewBg: '#F0FDFA',
    accentColor: '#0d9488',
    hasPhoto: true,
    category: 'Classic',
    emoji: '🟢',
  },
];
